# Generated by Django 3.1.6 on 2021-02-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'URL List',
            },
        ),
    ]
